local assert = require("luassert")
local util = require("tests.util")

describe("tests.util.buffer", function()
  it("creates a new buffer", function()
    local buf = util.buffer()
    assert.is_number(buf)
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, true)
    assert.equal(#lines, 3)
    assert.truthy(lines[1]:find("default content"))
    assert.equal(vim.api.nvim_get_option_value("filetype", { buf = buf }), "text")
  end)

  it("creates a new buffer with content", function()
    local buf = util.buffer("hello world")
    assert.is_number(buf)
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, true)
    assert.equal(#lines, 1)
    assert.equal(lines[1], "hello world")
    assert.equal(vim.api.nvim_get_option_value("filetype", { buf = buf }), "text")
  end)

  it("creates a new buffer with content and filetype", function()
    local buf = util.buffer('print("hello world")', "lua")
    assert.is_number(buf)
    local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, true)
    assert.equal(#lines, 1)
    assert.truthy(lines[1]:find("hello world"))
    assert.equal(vim.api.nvim_get_option_value("filetype", { buf = buf }), "lua")
  end)
end)
